export default [
  {
    name: "Prakher Prashank",
    github_username: "im-prakher",
    title: "Web Developer",
    facebook: "Prashank Prakher",
    twitter: "PrakherPrashank",
  },
  {
    name: "Aayush Kumar Sahu",
    github_username: "aayushmau5",
    title: "Web Developer",
    facebook: "",
    twitter: "aayushmau5",
  },
  {
  	name: "Aaryan Porwal",
  	github_username: "aaryanporwal",
  	title: "Explorer",
  	facebook: "",
  	twitter: "aaryan7476",
  },
  {
   name : "Ayush negi",
   github_username: "ayuushhh",
   title: "web_dev",
   facebook: "freakoayush",
   twitter: "",
  },
  { 
    name : "Aditya Pratap Singh Chauhan",
    github_username: "ADI1000b",
    title: "file",
    facebook: "",
    twitter: "",
  },
  { 
    name : "Dharmveer Singh",
    github_username: "moriarity9211",
    title: "file",
    facebook: "https://www.facebook.com/profile.php?id=100011387355705",
    twitter: "",
  },
  {
    name: "Sabreen Parveen",
    github_username: "sabreen-parveen",
    title: "",
    facebook: "",
    twitter: "",
  },
  {
    name: "Prashant Mishra",
    github_username: "PrimalPimmy",
    title:"Web Developer",
    facebook: "",
    twitter: "PrimalPimmy",
  },
  {
    name: "Harsh Upadhyay",
    github_username: "pyGitHub7",
    title: "Web Developer",
    facebook: "",
    twitter: "",
  },
  {
  	name: "Suryashankar Das",
  	github_username: "iamsdas",
  	title: "ML Enthusiast",
  	facebook: "",
  	twitter: "ssd_2002",
  },
  {
    name: "Ishan",
    github_username: "Ishan-Saini",
    title: "Web Developer",
    facebook: "",
    twitter: "im_Ishan24",
  },
   {
  	name: "Saksham Madan",
  	github_username: "Saksham1920",
  	title: "",
  	facebook: "",
  	twitter: "",
  },
  {
  	name: "Aachman Mittal",
  	github_username: "AarKiMos",
  	title: "OS and Aviation Enthusiast",
  	facebook: "",
  	twitter: "AarKiMos",
  },
  {
        name: "Isha R Mehta",
        github_username: "isha-24",
        title: "",
        facebook: "",
        twitter: "",
  },
  {
        name: "Dhruv Raj Kashyap",
        github_username: "dhruvrkashyap",
        title: "",
        facebook: "",
        twitter: "",
  },
  {
        name: "AKSHAT SRIVASTAVA",
        github_username: "KISLAYA-SRI",
        title: "Noob",
        facebook: "",
        twitter: "@AKSHAT_SRI_1",
  },
    {
        name: "Eshan Tripathi",
        github_username: "eshanheretic",
        title: "Web Developer",
        facebook: "",
        twitter: "",
    },
  {
	name: "Aarav Porwal",
	github_username: "aaravporwal",
	title: "Artist in making",
	facebook: "",
	twitter: "",
  },
  {
     name: "Kratika Garg",
     github_username: "kratikaatgithub",
     title: "",
     facebook: "",
     twitter: "",
 }
];
